### ISSUE TITLE
Connection Management/Timeouts

### ISSUE THREAD

**Issue by efxviet** [shotgunsoftware/python-api#5]
What's the recommended way to handle connection issues, i.e. slow or broken connections?

Is it safe just to use signals to cancel out of stalled/slow calls to the API?

**Comment by kporangehat** [comment]
You can [set the `timeout_secs` in the Config object](https://github.com/shotgunsoftware/python-api/blob/v3.0.29/shotgun_api3/shotgun.py#L242). Note that you can only set this after you've created an instance. And since by default, a new instance [connects to Shotgun when it's created](https://github.com/shotgunsoftware/python-api/blob/v3.0.29/shotgun_api3/shotgun.py#L470), there are two ways to make this work (as of v3.0.29):

1. Create the instance with `connect=False`. Then set the timeout:
  ```python
  sg = shotgun_api3.Shotgun(my_server, script_name="my_script", api_key="01234....", connect=False)
# set the timeout to 5 seconds
sg.config.timeout_secs = 5
```

2. Create your instance normally, set the timeout, then call `close()` to have the connection automatically recreated with your new timeout value the next time a connection is made:
  ```python
  sg = shotgun_api3.Shotgun(my_server, script_name="my_script", api_key="01234....")
# set the timeout to 5 seconds
sg.config.timeout_secs = 5
sg.close()
```
